---
name: Test

'on': push

jobs:
  main:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - self-hosted
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.0
      - run: mkdir .hidden-folder
      - run: touch .hidden-folder/file file
      - uses: docker://busybox:1
        with:
          entrypoint: sh
          args: -c "ls -aR $GITHUB_WORKSPACE"
      - uses: docker://busybox:1
        with:
          entrypoint: sh
          args: -c "ls -aR $(dirname $GITHUB_EVENT_PATH/..)"
      - uses: docker://busybox:1
        with:
          entrypoint: sh
          args: -c "ls -aR $HOME"
      - uses: ./
      - run: '! test -d .hidden-folder && ! test -f file'
